using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using Oxide.Core;
using Oxide.Core.Plugins;

namespace Oxide.Plugins
{
    [Info("Random Jump Items", "sdapro", "1.0.5")]
    public class RandomJumpItems : RustPlugin
    {
        private Dictionary<string, ItemConfig> itemConfig = new Dictionary<string, ItemConfig>
        {
			{ "rifle.ak", new ItemConfig{ Min = 1, Max = 1, Skins = new List<ulong> { 0 }, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.muzzlebrake", "weapon.mod.silencer","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "yellow.berry", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xylophone", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xmasdoorwreath", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xmas.window.garland", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xmas.tree", new ItemConfig { Min = 1, Max = 2 , Skins = new List<ulong> { 0} } },
			{ "xmas.present.small", new ItemConfig { Min = 30, Max = 300 , Skins = new List<ulong> { 0} } },
			{ "xmas.present.medium", new ItemConfig { Min = 2, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xmas.present.large", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xmas.lightstring", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xmas.lightstring.advanced", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xmas.double.door.garland", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xmas.door.garland", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xmas.decoration.tinsel", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xmas.decoration.star", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xmas.decoration.pinecone", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xmas.decoration.lights", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xmas.decoration.gingerbreadmen", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xmas.decoration.candycanes", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "xmas.decoration.baubels", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "wrappingpaper", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "wrappedgift", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "worm", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "workbench3", new ItemConfig { Min = 1, Max = 2 , Skins = new List<ulong> { 0} } },
			{ "workbench2", new ItemConfig { Min = 1, Max = 2 , Skins = new List<ulong> { 0} } },
			{ "workbench1", new ItemConfig { Min = 1, Max = 2 , Skins = new List<ulong> { 0} } },
			{ "woodtea.pure", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "woodtea", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "woodtea.advanced", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "woodmirror.standing", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "woodmirror.small", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "woodmirror.medium", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "woodmirror.large", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "woodframe.standing", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "woodframe.small", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "woodframe.medium", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "woodframe.large", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "woodcross", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "wood", new ItemConfig { Min = 1000, Max = 10000 , Skins = new List<ulong> { 0} } },
			{ "wood.armor.pants", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "wood.armor.jacket", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "wood.armor.helmet", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "wolfmeat.spoiled", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "wolfmeat.raw", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "wolfmeat.cooked", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "wolfmeat.burned", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "wiretool", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "whiteidtag", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "white.berry", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "weaponrack.light", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "weapon.mod.burstmodule", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "waterpump", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "waterjug", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "water.catcher.small", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "watchtower.wood", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "water.barrel", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "wantedposter", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "wall.window.glass.reinforced", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "wall.window.bars.wood", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "wall.window.bars.toptier", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "wall.window.bars.metal", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "wall.ice.wall", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "wall.graveyard.fence", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "wall.frame.shopfront.metal", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "wall.frame.netting", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "wall.frame.garagedoor", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "wall.frame.fence", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "wall.frame.fence.gate", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "wall.frame.cell", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "wall.frame.cell.gate", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "wall.external.high.stone", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "wall.external.high", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "wall.external.high.ice", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "walkietalkie", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "vending.machine", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "vehicle.2mod.passengers", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "vehicle.2mod.fuel.tank", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "vehicle.2mod.flatbed", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "vehicle.2mod.camper", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "vehicle.1mod.taxi", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "vehicle.1mod.storage", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "vehicle.1mod.rear.seats", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "vehicle.1mod.passengers.armored", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "vehicle.1mod.flatbed", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "vehicle.1mod.engine", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "vehicle.1mod.cockpit.with.engine", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "vehicle.1mod.cockpit", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "vehicle.1mod.cockpit.armored", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "vampire.stake", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "twowaymirror.window", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "twitchsunglasses", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "twitchrivals2023desk", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "twitch.headset", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "tunalight", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "tshirt.red", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "tshirt", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "valve3", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "valve2", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "valve1", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "tshirt.long", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "trophy2023", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "trophy", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "trap.landmine", new ItemConfig { Min = 1, Max = 15 , Skins = new List<ulong> { 0} } },
			{ "trap.bear", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "torchholder", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "torch.torch.skull", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "torch", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "toolgun", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "tool.instant_camera", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "tool.camera", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "tool.binoculars", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "tincan.alarm", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "telephone", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "techparts", new ItemConfig { Min = 5, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "tarp", new ItemConfig { Min = 5, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "targeting.computer", new ItemConfig { Min = 5, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "target.reactive", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "tactical.gloves", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "table", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "syringe.medical", new ItemConfig { Min = 2, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "surveycharge", new ItemConfig { Min = 1, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "supply.signal", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "supertea", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "sulfur", new ItemConfig { Min = 500, Max = 5000 , Skins = new List<ulong> { 0} } },
			{ "sulfur.ore", new ItemConfig { Min = 500, Max = 5000 , Skins = new List<ulong> { 0} } },
			{ "submarine.torpedo.straight", new ItemConfig { Min = 20, Max = 50 , Skins = new List<ulong> { 0} } },
			{ "strobelight", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "storage_barrel_c", new ItemConfig { Min = 1, Max = 3 , Skins = new List<ulong> { 0} } },
			{ "storage_barrel_b", new ItemConfig { Min = 1, Max = 3 , Skins = new List<ulong> { 0} } },
			{ "stones", new ItemConfig { Min = 1000, Max = 10000 , Skins = new List<ulong> { 0} } },
			{ "stonehatchet", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "stone.pickaxe", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "stocking.small", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "stocking.large", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "sticks", new ItemConfig { Min = 1, Max = 5555, Skins = new List<ulong> { 0} } },
			{ "stash.small", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "spraycan", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "spookyspeaker", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "spinner.wheel", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "spiderweb", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "speargun.spear", new ItemConfig { Min = 1, Max = 60 , Skins = new List<ulong> { 0} } },
			{ "speargun", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "spear.wooden", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "spear.wooden.cny_spear", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "spear.stone", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "spear.cny", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "sparkplug3", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "soundlight", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "sofa", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "sofa.pattern", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "snowman", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "snowmachine", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "snowballgun", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "snowball", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "smgbody", new ItemConfig { Min = 1, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "sparkplug1", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "smg.thompson", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.muzzlebrake", "weapon.mod.silencer","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "revolver.hc", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "mummymask", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hazmatsuit.frontier", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "jumpsuit.waterwellnpc", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "blunderbuss", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "frontier_hatchet", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "skidoo", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "frankensteinmask", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "smg.mp5", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.muzzlebrake", "weapon.mod.silencer","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "sparkplug2", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "smg.2", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.muzzlebrake", "weapon.mod.silencer","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "smart.switch", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "smart.alarm", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "smallwaterbottle", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "smallcandles", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "smallbackpack", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "small.oil.refinery", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "sleepingbag", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "sled.xmas", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "sled", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "skylantern.skylantern.red", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "skylantern.skylantern.purple", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "skylantern.skylantern.orange", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "skylantern.skylantern.green", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "skylantern", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "skullspikes.pumpkin", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "skullspikes", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "skullspikes.candles", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "skulldoorknocker", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "skull_fire_pit", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "skull.wolf", new ItemConfig { Min = 1, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "skull.trophy.table", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "skull.trophy", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "skull", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "skull.human", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "sign.wooden.small", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "sign.wooden.medium", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "sign.wooden.large", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "sign.wooden.huge", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "sign.post.single", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "sign.pole.banner.large", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "sign.neon.xl", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "sign.neon.xl.animated", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "sign.neon.125x215", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "sign.neon.125x215.animated", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "sign.neon.125x125", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "sickle", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "shutter.wood.a", new ItemConfig { Min = 1, Max = 15 , Skins = new List<ulong> { 0} } },
			{ "shutter.metal.embrasure.b", new ItemConfig { Min = 1, Max = 15 , Skins = new List<ulong> { 0} } },
			{ "shutter.metal.embrasure.a", new ItemConfig { Min = 1, Max = 15 , Skins = new List<ulong> { 0} } },
			{ "shovel", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "shotgun.waterpipe", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "shotgun.spas12", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.silencer","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "shotgun.pump", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.silencer","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "shotgun.m4", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.silencer","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "shotgun.double", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "shoes.boots", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "shirt.tanktop", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "shirt.collared", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "shelves", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "sheetmetal", new ItemConfig { Min = 1, Max = 40 , Skins = new List<ulong> { 0} } },
			{ "sewingkit", new ItemConfig { Min = 1, Max = 40 , Skins = new List<ulong> { 0} } },
			{ "semibody", new ItemConfig { Min = 1, Max = 40 , Skins = new List<ulong> { 0} } },
			{ "seed.yellow.berry", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "seed.white.berry", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "seed.red.berry", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "secretlabchair", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "searchlight", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "scraptransportheli.repair", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "scrapmirror.standing", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "scrapmirror.small", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "scrapframe.standing", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "scrapframe.large", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "scrap", new ItemConfig { Min = 50, Max = 1000 , Skins = new List<ulong> { 0} } },
			{ "scientistsuit_heavy", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "scarecrowhead", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "scarecrow.suit", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "scarecrow", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "santahat", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "santabeard", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "samsite", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "salvaged.sword", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "salvaged.cleaver", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "rustige_egg_f", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "rustige_egg_e", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "rustige_egg_d", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "rustige_egg_c", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "rustige_egg_b", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "rustige_egg_a", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "rug", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "rug.bear", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "rope", new ItemConfig { Min = 1, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "rockingchair", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "rocket.launcher", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0},Ammo = true } },
			{ "rocket.launcher.dragon", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0},Ammo = true } },
			{ "rock", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "roadsigns", new ItemConfig { Min = 1, Max = 50 , Skins = new List<ulong> { 0} } },
			{ "roadsign.kilt", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "roadsign.jacket", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "roadsign.gloves", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "riot.helmet", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "riflebody", new ItemConfig { Min = 1, Max = 50 , Skins = new List<ulong> { 0} } },
			{ "rifle.sks", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "rifle.semiauto.sks", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.silencer","weapon.mod.simplesight","weapon.mod.small.scope", "","","","","","",},Ammo = true}},
			{ "rifle.semiauto", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.silencer","weapon.mod.simplesight","weapon.mod.small.scope", "","","","","","",},Ammo = true}},
			{ "rifle.m39", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.muzzlebrake", "weapon.mod.silencer","weapon.mod.simplesight","weapon.mod.small.scope", "weapon.mod.8x.scope", "","","","","","",},Ammo = true}},
			{ "rifle.lr300", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.muzzlebrake", "weapon.mod.silencer","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "rifle.l96", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.silencer","weapon.mod.simplesight","weapon.mod.small.scope", "weapon.mod.8x.scope", "","","","","","",},Ammo = true}},
			{ "scraptea.pure", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "scraptea", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "scraptea.advanced", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "rifle.bolt", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.silencer","weapon.mod.simplesight","weapon.mod.small.scope", "weapon.mod.8x.scope", "","","","","","",},Ammo = true}},
			{ "rifle.ak.ice", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.muzzlebrake", "weapon.mod.silencer","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "rifle.ak.diver", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.muzzlebrake", "weapon.mod.silencer","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "rf_pager", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "rf.detonator", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "researchpaper", new ItemConfig { Min = 1, Max = 100 , Skins = new List<ulong> { 0} } },
			{ "research.table", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "redidtag", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "red.berry", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "rail.road.planter", new ItemConfig { Min = 1, Max = 2 , Skins = new List<ulong> { 0} } },
			{ "pumpkinbasket", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "propanetank", new ItemConfig { Min = 1, Max = 50 , Skins = new List<ulong> { 0} } },
			{ "prisonerhood", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "powered.water.purifier", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "pookie.bear", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "plantfiber", new ItemConfig { Min = 1, Max = 100 , Skins = new List<ulong> { 0} } },
			{ "planter.small", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "planter.large", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "pitchfork", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "pistol.water", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "pistol.semiauto", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.silencer","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "pistol.revolver", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> {"weapon.mod.silencer","",},Ammo = true}},
			{ "pistol.python", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "pistol.prototype17", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.muzzlebrake", "weapon.mod.silencer","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "pistol.nailgun", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0},Ammo = true } },
			{ "pistol.m92", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.silencer","weapon.mod.simplesight", "","","","","","",},Ammo = true}},
			{ "pistol.eoka", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "pipetool", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "pinata", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "pickaxe", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "piano", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "partyhat", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "parachute", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "pants", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "paddle", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "paddlingpool", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "nightvisiongoggles", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "newyeargong", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "multiplegrenadelauncher", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0},Ammo = true } },
			{ "movembermoustachecard", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "movembermoustache", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "modularcarlift", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "mixingtable", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "minigun", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0},Ammo = true } },
			{ "minecart.planter", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "military flamethrower", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0},Ammo = true } },
			{ "microphonestand", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "metal.plate.torso", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "metal.plate.torso.icevest", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "metal.ore", new ItemConfig { Min = 1000, Max = 5000 , Skins = new List<ulong> { 0} } },
			{ "metal.fragments", new ItemConfig { Min = 100, Max = 3000 , Skins = new List<ulong> { 0} } },
			{ "metal.facemask", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "piston2", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "piston1", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "pinkidtag", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "photoframe.portrait", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "oretea.pure", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "oretea", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "oretea.advanced", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "orangeidtag", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "mushroom", new ItemConfig { Min = 10, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "metalspring", new ItemConfig { Min = 1, Max = 50 , Skins = new List<ulong> { 0} } },
			{ "metalpipe", new ItemConfig { Min = 1, Max = 50 , Skins = new List<ulong> { 0} } },
			{ "metalblade", new ItemConfig { Min = 1, Max = 50 , Skins = new List<ulong> { 0} } },
			{ "metal.refined", new ItemConfig { Min = 50, Max = 300 , Skins = new List<ulong> { 0} } },
			{ "metal.facemask.icemask", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "metal.facemask.hockey", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "metal.detector", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "megaphone", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "mask.bandana.skull.red.skin", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "mask.bandana", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "mask.balaclava", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "machete", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "meat.pork.cooked", new ItemConfig { Min = 10, Max = 50 , Skins = new List<ulong> { 0} } },
			{ "meat.pork.burned", new ItemConfig { Min = 10, Max = 50 , Skins = new List<ulong> { 0} } },
			{ "meat.boar", new ItemConfig { Min = 10, Max = 50 , Skins = new List<ulong> { 0} } },
			{ "maxhealthtea.pure", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "maxhealthtea", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "maxhealthtea.advanced", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "mace", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "mace.baseballbat", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "lumberjack.pickaxe", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "lumberjack.hatchet", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "lumberjack hoodie", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "lowgradefuel", new ItemConfig { Min = 50, Max = 200 , Skins = new List<ulong> { 0} } },
			{ "longsword", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "lmg.m249", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.muzzlebrake", "weapon.mod.silencer","weapon.mod.simplesight","weapon.mod.small.scope", "weapon.mod.8x.scope", "","","","","","",},Ammo = true}},
			{ "legacyfurnace", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "legacy bow", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Ammo = true  }},
			{ "legacy.shelter.wood", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "largebackpack", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "knife.skinning", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "knife.combat", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "lunar.firecrackers", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "locker", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "lock.key", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "lock.code", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "knife.butcher", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "knife.bone", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "jumpsuit.suit", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "jumpsuit.suit.blue", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "jackhammer", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "jacket.snow", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "jacket", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "innertube", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "icepick.salvaged", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hosetool", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "horse.shoes.basic", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "horse.shoes.advanced", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "horse.saddle.single", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "horse.armor.wood", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "horse.armor.roadsign", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hoodie", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "homingmissile.launcher", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0},Ammo = true } },
			{ "hobobarrel", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hmlmg", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Mods = new List<string> { "weapon.mod.extendedmags", "weapon.mod.flashlight", "weapon.mod.holosight", "weapon.mod.lasersight", "weapon.mod.muzzleboost", "weapon.mod.muzzlebrake", "weapon.mod.silencer","weapon.mod.simplesight","weapon.mod.small.scope", "weapon.mod.8x.scope", "","","","","","",},Ammo = true}},
			{ "hitchtroughcombo", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "heavy.plate.pants", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "heavy.plate.jacket", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "heavy.plate.helmet", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "head.bag", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hazmatsuittwitch", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hazmatsuit_scientist_peacekeeper", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hazmatsuit_scientist_nvgm", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hazmatsuit_scientist_arctic", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hazmatsuit_scientist", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hazmatsuit.spacesuit", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hazmatsuit", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hazmatsuit.nomadsuit", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hazmatsuit.lumberjack", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hazmatsuit.diver", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hazmatsuit.arcticsuit", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hatchet", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hat.wolf", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hat.tigermask", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hat.ratmask", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hat.rabbitmask", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hat.oxmask", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hat.miner", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hat.gas.mask", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hat.dragonmask", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hat.cap", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hat.candle", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hat.bunnyhat", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hat.boonie", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hat.beenie", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hammer.salvaged", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "hammer", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "halloween.surgeonsuit", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "halloween.mummysuit", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "gunrack_wide.horizontal", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "gunrack_tall.horizontal", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "gunrack_stand", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "gunrack.single.3.horizontal", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "gunrack.single.2.horizontal", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "gunrack.single.1.horizontal", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "gunrack.horizontal", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "gunpowder", new ItemConfig { Min = 100, Max = 2000 , Skins = new List<ulong> { 0} } },
			{ "gun.water", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "gloweyes", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "gingerbreadsuit", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "giantlollipops", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "giantcandycanedecor", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "ghostsheet", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "generator.wind.scrap", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "geiger.counter", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "gears", new ItemConfig { Min = 5, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "gates.external.high.wood", new ItemConfig { Min = 1, Max = 2 , Skins = new List<ulong> { 0} } },
			{ "gates.external.high.stone", new ItemConfig { Min = 1, Max = 2 , Skins = new List<ulong> { 0} } },
			{ "furnace", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "furnace.large", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "fun.tuba", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "fun.trumpet", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "fun.tambourine", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "fun.jerrycanguitar", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "fun.guitar", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "fun.flute", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "fun.cowbell", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "fun.boomboxportable", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "fun.bass", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "fridge", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "fogmachine", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "floor.triangle.ladder.hatch", new ItemConfig { Min = 1, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "floor.triangle.grill", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "floor.ladder.hatch", new ItemConfig { Min = 1, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "floor.grill", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "flashlight.held", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "flare", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "flameturret", new ItemConfig { Min = 1, Max = 2 , Skins = new List<ulong> { 0} } },
			{ "flamethrower", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "fishtrophy", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "fishtrap.small", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "fishingrod.handmade", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "fish.yellowperch", new ItemConfig { Min = 1, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "fish.troutsmall", new ItemConfig { Min = 1, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "fish.smallshark", new ItemConfig { Min = 1, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "fireplace.stone", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "fertilizer", new ItemConfig { Min = 100, Max = 1000 , Skins = new List<ulong> { 0} } },
			{ "fat.animal", new ItemConfig { Min = 100, Max = 500 , Skins = new List<ulong> { 0} } },
			{ "factorydoor", new ItemConfig { Min = 1, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "explosives", new ItemConfig { Min = 10, Max = 50 , Skins = new List<ulong> { 0} } },
			{ "explosive.timed", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "explosive.satchel", new ItemConfig { Min = 2, Max = 15 , Skins = new List<ulong> { 0} } },
			{ "electric.splitter", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "electric.solarpanel.large", new ItemConfig { Min = 1, Max = 2 , Skins = new List<ulong> { 0} } },
			{ "electric.sirenlight", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "electric.fuelgenerator.small", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "electric.battery.rechargable.small", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "electric.battery.rechargable.medium", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "electric.battery.rechargable.large", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "electric.audioalarm", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "electric.andswitch", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "easterdoorwreath", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "easterbasket", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "easter.silveregg", new ItemConfig { Min = 3, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "easter.paintedeggs", new ItemConfig { Min = 100, Max = 3000 , Skins = new List<ulong> { 0} } },
			{ "easter.goldegg", new ItemConfig { Min = 1, Max = 2 , Skins = new List<ulong> { 0} } },
			{ "easter.bronzeegg", new ItemConfig { Min = 5, Max = 70 , Skins = new List<ulong> { 0} } },
			{ "drumkit", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "dropbox", new ItemConfig { Min = 1, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "drone", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "dragondoorknocker", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "draculamask", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "draculacape", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "door.hinged.wood", new ItemConfig { Min = 1, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "door.hinged.toptier", new ItemConfig { Min = 1, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "door.hinged.metal", new ItemConfig { Min = 1, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "door.hinged.industrial.a", new ItemConfig { Min = 1, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "door.double.hinged.wood", new ItemConfig { Min = 1, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "door.double.hinged.toptier", new ItemConfig { Min = 1, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "door.double.hinged.metal", new ItemConfig { Min = 1, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "door.double.hinged.bardoors", new ItemConfig { Min = 1, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "door.closer", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "dogtagneutral", new ItemConfig { Min = 1, Max = 500 , Skins = new List<ulong> { 0} } },
			{ "diving.wetsuit", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "diving.tank", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "diving.mask", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "diving.fins", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "divertorch", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "diverpickaxe", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "diverhatchet", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "discofloor", new ItemConfig { Min = 2, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "discofloor.largetiles", new ItemConfig { Min = 2, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "discoball", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "diesel_barrel", new ItemConfig { Min = 5, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "deer.skull.mask", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "cursedcauldron", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "cupboard.tool.shockbyte", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "cupboard.tool.retro", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "cupboard.tool", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "crude.oil", new ItemConfig { Min = 30, Max = 100 , Skins = new List<ulong> { 0} } },
			{ "crossbow", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Ammo = true } },
			{ "cratecostume", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "connected.speaker", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "concretepickaxe", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "concretehatchet", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "computerstation", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "composter", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "coffin.storage", new ItemConfig { Min = 1, Max = 2 , Skins = new List<ulong> { 0} } },
			{ "coffeecan.helmet", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "clatter.helmet", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "chicken.costume", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "chainsaw", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "ceilinglight", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "cctv.camera", new ItemConfig { Min = 1, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "cassette.short", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "candycaneclub", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "candycane", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "campfire", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "cakefiveyear", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "burlap.trousers", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "burlap.shoes", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "burlap.shirt", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "burlap.headwrap", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "burlap.gloves", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "burlap.gloves.new", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "building.planner", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "bucket.water", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "bucket.helmet", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "bow.hunting", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "bow.compound", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Ammo = true } },
			{ "botabag", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0}, Ammo = true  } },
			{ "boots.frog", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "boombox", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "boogieboard", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "bone.club", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "bone.fragments", new ItemConfig { Min = 100, Max = 500 , Skins = new List<ulong> { 0} } },
			{ "bone.armor.suit", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "bed", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "beachtowel", new ItemConfig { Min = 1, Max = 2 , Skins = new List<ulong> { 0} } },
			{ "bbq", new ItemConfig { Min = 1, Max = 3 , Skins = new List<ulong> { 0} } },
			{ "axe.salvaged", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "autoturret", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "attire.snowman.helmet", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "attire.reindeer.headband", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "attire.ninja.suit", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "attire.nesthat", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "attire.hide.vest", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "attire.hide.skirt", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "attire.hide.poncho", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "attire.hide.pants", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "attire.hide.helterneck", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "attire.hide.boots", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "attire.egg.suit", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "attire.bunnyears", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "attire.bunny.onesie", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "attire.banditguard", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "arcade.machine.chippy", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "abovegroundpool", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "aiming.module.mlrs", new ItemConfig { Min = 1, Max = 1 , Skins = new List<ulong> { 0} } },
			{ "ammo.grenadelauncher.buckshot", new ItemConfig { Min = 6, Max = 16 , Skins = new List<ulong> { 0} } },
			{ "ammo.grenadelauncher.he", new ItemConfig { Min = 5, Max = 15 , Skins = new List<ulong> { 0} } },
			{ "ammo.grenadelauncher.smoke", new ItemConfig { Min = 5, Max = 17 , Skins = new List<ulong> { 0} } },
			{ "ammo.handmade.shell", new ItemConfig { Min = 20, Max = 90 , Skins = new List<ulong> { 0} } },
			{ "ammo.nailgun.nails", new ItemConfig { Min = 30, Max = 200 , Skins = new List<ulong> { 0} } },
			{ "ammo.pistol.fire", new ItemConfig { Min = 30, Max = 450 , Skins = new List<ulong> { 0} } },
			{ "ammo.pistol.hv", new ItemConfig { Min = 30, Max = 450 , Skins = new List<ulong> { 0} } },
			{ "ammo.pistol", new ItemConfig { Min = 30, Max = 450 , Skins = new List<ulong> { 0} } },
			{ "ammo.rifle.explosive", new ItemConfig { Min = 10, Max = 100 , Skins = new List<ulong> { 0} } },
			{ "ammo.rifle.hv", new ItemConfig { Min = 30, Max = 450 , Skins = new List<ulong> { 0} } },
			{ "ammo.rifle.incendiary", new ItemConfig { Min = 30, Max = 450 , Skins = new List<ulong> { 0} } },
			{ "ammo.rifle", new ItemConfig { Min = 30, Max = 450 , Skins = new List<ulong> { 0} } },
			{ "ammo.rocket.basic", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "ammo.rocket.fire", new ItemConfig { Min = 1, Max = 6 , Skins = new List<ulong> { 0} } },
			{ "ammo.rocket.hv", new ItemConfig { Min = 1, Max = 6 , Skins = new List<ulong> { 0} } },
			{ "ammo.rocket.mlrs", new ItemConfig { Min = 1, Max = 6 , Skins = new List<ulong> { 0} } },
			{ "ammo.rocket.sam", new ItemConfig { Min = 20, Max = 100 , Skins = new List<ulong> { 0} } },
			{ "ammo.shotgun.fire", new ItemConfig { Min = 10, Max = 70 , Skins = new List<ulong> { 0} } },
			{ "ammo.shotgun", new ItemConfig { Min = 10, Max = 70 , Skins = new List<ulong> { 0} } },
			{ "ammo.shotgun.slug", new ItemConfig { Min = 10, Max = 70 , Skins = new List<ulong> { 0} } },
			{ "antiradpills", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "apple", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "apple.spoiled", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "arrow.bone", new ItemConfig { Min = 20, Max = 150 , Skins = new List<ulong> { 0} } },
			{ "arrow.fire", new ItemConfig { Min = 20, Max = 150 , Skins = new List<ulong> { 0} } },
			{ "arrow.hv", new ItemConfig { Min = 20, Max = 150 , Skins = new List<ulong> { 0} } },
			{ "arrow.wooden", new ItemConfig { Min = 20, Max = 150 , Skins = new List<ulong> { 0} } },
			{ "barricade.concrete", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "barricade.metal", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "barricade.sandbags", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "barricade.stone", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "barricade.wood.cover", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "barricade.wood", new ItemConfig { Min = 1, Max = 3 , Skins = new List<ulong> { 0} } },
			{ "beachchair", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "beachparasol", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "beachtable", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "bearmeat.burned", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "bearmeat.cooked", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "bearmeat", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "black.berry", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "black.raspberries", new ItemConfig { Min = 1, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "blue.berry", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "blood", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "blueberries", new ItemConfig { Min = 1, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "blueidtag", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "bottle.vodka", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "box.repair.bench", new ItemConfig { Min = 1, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "box.wooden.large", new ItemConfig { Min = 1, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "box.wooden", new ItemConfig { Min = 1, Max = 4 , Skins = new List<ulong> { 0} } },
			{ "cactusflesh", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "can.beans.empty", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "can.beans", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "can.tuna.empty", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "can.tuna", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "carburetor1", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "carburetor2", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "carburetor3", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "chair.icethrone", new ItemConfig { Min = 1, Max = 2 , Skins = new List<ulong> { 0} } },
			{ "chair", new ItemConfig { Min = 1, Max = 2 , Skins = new List<ulong> { 0} } },
			{ "charcoal", new ItemConfig { Min = 100, Max = 4000 , Skins = new List<ulong> { 0} } },
			{ "chicken.burned", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "chicken.cooked", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "chicken.raw", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "chicken.spoiled", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "chineselantern", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "chineselanternwhite", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "chocolate", new ItemConfig { Min = 1, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "cloth", new ItemConfig { Min = 30, Max = 500 , Skins = new List<ulong> { 0} } },
			{ "confetticannon", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "corn", new ItemConfig { Min = 1, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "crankshaft1", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "crankshaft2", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "crankshaft3", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "deermeat.burned", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "deermeat.cooked", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "deermeat.raw", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "ducttape", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "fish.anchovy", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "fish.catfish", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "fish.cooked", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "fish.herring", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "fish.minnows", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "fish.orangeroughy", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "fish.raw", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "fish.salmon", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "fish.sardine", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "fuse", new ItemConfig { Min = 5, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "glue", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "granolabar", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "grenade.beancan", new ItemConfig { Min = 1, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "grenade.f1", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "grenade.flashbang", new ItemConfig { Min = 1, Max = 10 , Skins = new List<ulong> { 0} } },
			{ "grenade.molotov", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "grenade.smoke", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "grub", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "halloween.lootbag.small", new ItemConfig { Min = 10, Max = 250 , Skins = new List<ulong> { 0} } },
			{ "halloween.lootbag.medium", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "halloween.lootbag.large", new ItemConfig { Min = 1, Max = 2 , Skins = new List<ulong> { 0} } },
			{ "halloween.candy", new ItemConfig { Min = 100, Max = 2550 , Skins = new List<ulong> { 0} } },
			{ "guntrap", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "handcuffs", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "healingtea.advanced", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "healingtea", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "healingtea.pure", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "horsedung", new ItemConfig { Min = 50, Max = 250 , Skins = new List<ulong> { 0} } },
			{ "horsemeat.burned", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "horsemeat.cooked", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "horsemeat.raw", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "hq.metal.ore", new ItemConfig { Min = 50, Max = 300 , Skins = new List<ulong> { 0} } },
			{ "humanmeat.burned", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "humanmeat.cooked", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "humanmeat.raw", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "humanmeat.spoiled", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "jackolantern.angry", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "jackolantern.happy", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "jar.pickle", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "ladder.wooden.wall", new ItemConfig { Min = 1, Max = 3 , Skins = new List<ulong> { 0} } },
			{ "lantern", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "largecandles", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "leather", new ItemConfig { Min = 100, Max = 1000 , Skins = new List<ulong> { 0} } },
			{ "lavenderidtag", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "laserlight", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "largemedkit", new ItemConfig { Min = 1, Max = 5 , Skins = new List<ulong> { 0} } },
			{ "radiationresisttea.pure", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "radiationresisttea", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "radiationresisttea.advanced", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "radiationremovetea.pure", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "radiationremovetea", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "radiationremovetea.advanced", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "purpleidtag", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "pumpkin", new ItemConfig { Min = 10, Max = 50 , Skins = new List<ulong> { 0} } },
			{ "ptz.cctv.camera", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
			{ "potato", new ItemConfig { Min = 10, Max = 30 , Skins = new List<ulong> { 0} } },
			{ "piston3", new ItemConfig { Min = 1, Max = 20 , Skins = new List<ulong> { 0} } },
            { "bandage", new ItemConfig { Min = 2, Max = 40 , Skins = new List<ulong> { 0} } },
        };

        private List<string> blockList = new List<string> { "rock" };
        private Dictionary<BasePlayer, float> lastJumpTimes = new Dictionary<BasePlayer, float>();
        private Dictionary<BasePlayer, bool> playerLootSettings = new Dictionary<BasePlayer, bool>();


        private void Init()
        {
            Puts("RandomJumpItems plugin loaded.");
        }

        public bool IsRandomLootEnabled(BasePlayer player)
        {
            return playerLootSettings.TryGetValue(player, out bool isEnabled) ? isEnabled : true;
        }

        [ChatCommand("toggleloot")]
        private void ToggleRandomLoot(BasePlayer player, string command, string[] args)
        {
            bool currentState = IsRandomLootEnabled(player);
            playerLootSettings[player] = !currentState;
            player.ChatMessage($"Random loot is now {(playerLootSettings[player] ? "enabled" : "disabled")}.");
        }


        private void OnPlayerInput(BasePlayer player, InputState input)
        {
            if (player == null || !IsRandomLootEnabled(player)) return;
            if (!input.WasJustPressed(BUTTON.JUMP)) return;

            if (lastJumpTimes.TryGetValue(player, out float lastJumpTime) && Time.time - lastJumpTime < 0.7f)
            {
                return;
            }

            lastJumpTimes[player] = Time.time;
            GiveRandomItem(player);
        }

        private void GiveRandomItem(BasePlayer player)
        {
            if (player == null || !IsRandomLootEnabled(player)) return;

            var availableItems = itemConfig.Keys.Except(blockList).ToList();
            if (availableItems.Count == 0)
            {
                Puts("No items available to give.");
                return;
            }

            var itemName = availableItems[UnityEngine.Random.Range(0, availableItems.Count)];
            if (!itemConfig.TryGetValue(itemName, out var config)) return;

            int count = UnityEngine.Random.Range(config.Min, config.Max + 1);
            ItemDefinition itemDefinition = ItemManager.FindItemDefinition(itemName);
            if (itemDefinition == null)
            {
                Puts($"Item {itemName} not found.");
                return;
            }

            var item = ItemManager.CreateByItemID(itemDefinition.itemid, count);
            if (item == null) return;

            if (config.Skins?.Count > 0)
            {
                item.skin = config.Skins[UnityEngine.Random.Range(0, config.Skins.Count)];
            }

            if (config.Ammo && item.GetHeldEntity() is BaseProjectile weapon && weapon.primaryMagazine != null)
            {
                weapon.primaryMagazine.contents = weapon.primaryMagazine.capacity;
                weapon.SendNetworkUpdateImmediate();
            }

            if (config.Mods?.Count > 0 && item.contents != null)
            {
                var selectedMods = config.Mods.OrderBy(x => UnityEngine.Random.value).Take(UnityEngine.Random.Range(1, 4)).ToList();
                foreach (var modName in selectedMods)
                {
                    var mod = ItemManager.CreateByName(modName, 1);
                    if (mod != null)
                    {
                        item.contents.AddItem(mod.info, 1);
                    }
                }
            }

            player.GiveItem(item);
        }

        private class ItemConfig
        {
            public int Min { get; set; }
            public int Max { get; set; }
            public List<ulong> Skins { get; set; } = new List<ulong>();
            public List<string> Mods { get; set; } = new List<string>();
            public bool Ammo { get; set; } = false;
        }
    }
}
